name: tldr
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.3.1+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive: ^3.1.6
  bubble_tab_indicator: ^0.1.6
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flappy_search_bar_fork: ^1.7.4
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_typeahead: ^3.2.4
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  markdown_widget:
    git: https://github.com/asjqkkkk/markdown_widget
  path_provider: ^2.0.8
  url_launcher: ^6.0.17
  
dev_dependencies:
  import_sorter: ^4.6.0
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tldr.png"

flutter_native_splash:
  image: "assets/images/tldr.png"
  color: "#17181c"
  android12: true

dependency_overrides:
  markdown: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: icons
      fonts:
        - asset: assets/fonts/icons.ttf
