name: Update tldr commands file

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */6 * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r ./tldrdict/requirements.txt

      - name: Execute Python script
        run: |
          cd tldrdict
          python update.py
          update_pages.sh

      - name: setup git config
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}

      - name: commit changes
        run: |
          ./tldrdict/commit.sh
